---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: page
  label: Pages
  create: all
  match: "**/*.md"
- type: directory
  path: blog
  label: Blog
  create: documents
  match: "**/*.md"
- type: document
  path: data/theme.json
  label: Theme config
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
instant_preview: 
build:
  preview_output_directory: ".vuepress/dist"
  install_dependencies_command: yarn install
  preview_docker_image: node:10
  mount_path: "/srv"
  instant_preview_command: vuepress dev -p 8080 -h 0.0.0.0
  publish_command: vuepress build -d .vuepress/dist
  output_directory: ".vuepress/dist"
  preview_command: vuepress build -d .vuepress/dist
